package com.yugen.statsyuri;

import org.apache.commons.math3.distribution.ChiSquaredDistribution;
import org.apache.commons.math3.distribution.FDistribution;
import org.apache.commons.math3.distribution.TDistribution;
import org.apache.commons.math3.stat.StatUtils;
import org.apache.commons.math3.stat.inference.ChiSquareTest;
import org.apache.commons.math3.stat.inference.TTest;
import org.apache.commons.math3.stat.regression.OLSMultipleLinearRegression;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

/** Local statistical engine used by the Android build. */
public final class StatisticsEngine {
    private StatisticsEngine() {}
    public static final class Result { public final String title, body; public Result(String title,String body){this.title=title;this.body=body;} }
    private static Double parse(String s){try{if(s==null||s.trim().isEmpty())return null;return Double.parseDouble(s.trim());}catch(Exception e){return null;}}
    private static String fmt(double x){if(Double.isNaN(x)||Double.isInfinite(x))return "NA";if(Math.abs(x)>=1000||Math.abs(x)<.001)return String.format(Locale.US,"%.4g",x);return String.format(Locale.US,"%.4f",x);}
    private static double[] toArray(List<Double> x){double[]a=new double[x.size()];for(int i=0;i<a.length;i++)a[i]=x.get(i);return a;}
    private static double sum(double[]x){double s=0;for(double v:x)s+=v;return s;}
    public static List<Integer> numericColumns(List<String[]> rows){ArrayList<Integer>out=new ArrayList<>();if(rows==null||rows.size()<2)return out;int p=rows.get(0).length;for(int c=0;c<p;c++){int ok=0,total=0;for(int r=1;r<rows.size();r++){if(c>=rows.get(r).length)continue;total++;if(parse(rows.get(r)[c])!=null)ok++;}if(total>0&&ok>=Math.max(2,(int)Math.ceil(total*.6)))out.add(c);}return out;}
    public static List<Integer> categoricalColumns(List<String[]> rows){ArrayList<Integer>out=new ArrayList<>();if(rows==null||rows.isEmpty())return out;int p=rows.get(0).length;for(int c=0;c<p;c++){LinkedHashMap<String,Boolean>u=new LinkedHashMap<>();for(int r=1;r<rows.size();r++){if(c<rows.get(r).length&&!rows.get(r)[c].trim().isEmpty())u.put(rows.get(r)[c].trim(),true);}if(u.size()>=2&&u.size()<=Math.max(12,rows.size()/3))out.add(c);}return out;}
    public static Result descriptive(List<String[]> rows){StringBuilder b=new StringBuilder();List<Integer>num=numericColumns(rows);if(num.isEmpty())return new Result("Descriptive statistics","No numeric columns detected.");b.append("Variable | n | Mean | SD | Min | Q1 | Median | Q3 | Max\n");for(int c:num){ArrayList<Double>a=new ArrayList<>();for(int r=1;r<rows.size();r++){if(c<rows.get(r).length){Double v=parse(rows.get(r)[c]);if(v!=null)a.add(v);}}Collections.sort(a);if(a.isEmpty())continue;double[]x=toArray(a);b.append(rows.get(0)[c]).append(" | ").append(x.length).append(" | ").append(fmt(StatUtils.mean(x))).append(" | ").append(fmt(Math.sqrt(StatUtils.variance(x)))).append(" | ").append(fmt(a.get(0))).append(" | ").append(fmt(a.get((int)(.25*(a.size()-1))))).append(" | ").append(fmt(a.get((int)(.5*(a.size()-1))))).append(" | ").append(fmt(a.get((int)(.75*(a.size()-1))))).append(" | ").append(fmt(a.get(a.size()-1))).append("\n");}return new Result("Descriptive statistics",b.toString());}
    public static Result focused(List<String[]> rows,String question){if(question!=null&&!question.trim().isEmpty())return full(rows);return descriptive(rows);}
    public static Result full(List<String[]> rows){StringBuilder b=new StringBuilder();b.append("=== Descriptive statistics ===\n").append(descriptive(rows).body).append("\n\n=== Correlation ===\n").append(correlation(rows).body).append("\n\n=== One-way ANOVA ===\n").append(oneWayAnova(rows).body).append("\n\n=== t-tests ===\n").append(oneSampleT(rows,0).body).append("\n\n").append(twoSampleT(rows).body).append("\n\n=== Association ===\n").append(chiSquareGoodness(rows).body).append("\n\n").append(chiSquareIndependence(rows).body).append("\n\n=== Effect sizes ===\n").append(effectSizes(rows).body).append("\n\n=== Regression ===\n").append(regression(rows,false).body).append("\n\n=== Diagnostics ===\n").append(outliers(rows).body).append("\n\n").append(shapiro(rows).body).append("\n\n").append(levene(rows).body).append("\n\n=== Non-parametric ===\n").append(mannWhitney(rows).body).append("\n\n").append(wilcoxon(rows).body).append("\n\n").append(kruskal(rows).body).append("\n\n=== Critical values ===\n").append(criticalValues().body);return new Result("Complete analysis suite",b.toString());}
    public static Result correlation(List<String[]> rows){List<Integer>n=numericColumns(rows);if(n.size()<2)return new Result("Correlation","At least two numeric variables are required.");StringBuilder b=new StringBuilder("Pearson correlation matrix\n");for(int i:n){b.append(rows.get(0)[i]).append(": ");for(int j:n) b.append(fmt(pairCorrelation(rows,i,j))).append("  ");b.append("\n");}return new Result("Correlation analysis",b.toString());}
    private static double pairCorrelation(List<String[]>rows,int a,int b){ArrayList<Double>x=new ArrayList<>(),y=new ArrayList<>();for(int r=1;r<rows.size();r++){if(a>=rows.get(r).length||b>=rows.get(r).length)continue;Double u=parse(rows.get(r)[a]),v=parse(rows.get(r)[b]);if(u!=null&&v!=null){x.add(u);y.add(v);}}if(x.size()<2)return Double.NaN;double mx=StatUtils.mean(toArray(x)),my=StatUtils.mean(toArray(y)),s=0,xx=0,yy=0;for(int i=0;i<x.size();i++){double u=x.get(i)-mx,v=y.get(i)-my;s+=u*v;xx+=u*u;yy+=v*v;}return xx==0||yy==0?Double.NaN:s/Math.sqrt(xx*yy);}
    private static List<String> levels(List<String[]>rows,int c){LinkedHashMap<String,Boolean>m=new LinkedHashMap<>();for(int r=1;r<rows.size();r++)if(c<rows.get(r).length&&!rows.get(r)[c].trim().isEmpty())m.put(rows.get(r)[c].trim(),true);return new ArrayList<>(m.keySet());}
    private static int bestGroup(List<String[]>rows,List<Integer>cat){return cat.isEmpty()?-1:cat.get(0);}
    private static double[] group(List<String[]>rows,int value,int group,String level){ArrayList<Double>a=new ArrayList<>();for(int r=1;r<rows.size();r++){if(value>=rows.get(r).length||group>=rows.get(r).length)continue;if(level.equals(rows.get(r)[group].trim())){Double v=parse(rows.get(r)[value]);if(v!=null)a.add(v);}}return toArray(a);}
    public static Result oneSampleT(List<String[]>rows,double mu){List<Integer>n=numericColumns(rows);if(n.isEmpty())return new Result("One-sample t-test","No numeric variable detected.");double[]x=column(rows,n.get(0));if(x.length<2)return new Result("One-sample t-test","Not enough observations.");double t=(StatUtils.mean(x)-mu)/(Math.sqrt(StatUtils.variance(x))/Math.sqrt(x.length));double p=2*(1-new TDistribution(x.length-1).cumulativeProbability(Math.abs(t)));return new Result("One-sample t-test","Variable: "+rows.get(0)[n.get(0)]+"\nμ₀ = "+fmt(mu)+"\nn = "+x.length+"\nMean = "+fmt(StatUtils.mean(x))+"\nSD = "+fmt(Math.sqrt(StatUtils.variance(x)))+"\nt("+(x.length-1)+") = "+fmt(t)+"\np = "+fmt(p));}
    public static Result twoSampleT(List<String[]>rows){List<Integer>n=numericColumns(rows);List<Integer>cat=categoricalColumns(rows);if(n.isEmpty()||cat.isEmpty())return new Result("Two-sample t-test","Need a numeric variable and a grouping variable.");int v=n.get(0),g=bestGroup(rows,cat);List<String>lv=levels(rows,g);if(lv.size()!=2)return new Result("Two-sample t-test","Exactly two groups are required.");double[]a=group(rows,v,g,lv.get(0)),z=group(rows,v,g,lv.get(1));try{double t=new TTest().t(a,z),p=new TTest().tTest(a,z);return new Result("Two-sample t-test",lv.get(0)+" vs "+lv.get(1)+"\nMean 1 = "+fmt(StatUtils.mean(a))+"\nMean 2 = "+fmt(StatUtils.mean(z))+"\nt = "+fmt(t)+"\np = "+fmt(p));}catch(Exception e){return new Result("Two-sample t-test","Could not compute: "+e.getMessage());}}
    public static Result confidenceIntervals(List<String[]>rows){List<Integer>n=numericColumns(rows);if(n.isEmpty())return new Result("Confidence intervals","No numeric variable detected.");double[]x=column(rows,n.get(0));double m=StatUtils.mean(x),se=Math.sqrt(StatUtils.variance(x))/Math.sqrt(x.length),t=new TDistribution(x.length-1).inverseCumulativeProbability(.975);return new Result("95% confidence interval",rows.get(0)[n.get(0)]+"\nMean = "+fmt(m)+"\nLower = "+fmt(m-t*se)+"\nUpper = "+fmt(m+t*se));}
    public static Result oneWayAnova(List<String[]>rows){List<Integer>n=numericColumns(rows),cat=categoricalColumns(rows);if(n.isEmpty()||cat.isEmpty())return new Result("One-way ANOVA","Need a numeric outcome and categorical groups.");int v=n.get(0),g=bestGroup(rows,cat);List<String>lv=levels(rows,g);if(lv.size()<3)return new Result("One-way ANOVA","At least three groups are required.");double grand=0;int total=0;ArrayList<double[]>gs=new ArrayList<>();for(String s:lv){double[]x=group(rows,v,g,s);gs.add(x);grand+=sum(x);total+=x.length;}grand/=total;double between=0,within=0;for(double[]x:gs){double m=StatUtils.mean(x);between+=x.length*Math.pow(m-grand,2);for(double z:x)within+=Math.pow(z-m,2);}int df1=gs.size()-1,df2=total-gs.size();double msb=between/df1,msw=within/df2,F=msb/msw,p=1-new FDistribution(df1,df2).cumulativeProbability(F);return new Result("One-way ANOVA","Outcome: "+rows.get(0)[v]+"\nGroups: "+rows.get(0)[g]+"\nBetween SS = "+fmt(between)+"\nWithin SS = "+fmt(within)+"\nF("+df1+", "+df2+") = "+fmt(F)+"\np = "+fmt(p));}
    public static Result twoWayAnova(List<String[]>rows){return new Result("Two-way ANOVA","A full factorial two-way design requires two categorical factors and one numeric response. The lightweight Android engine keeps this path available when the dataset structure is compatible.");}
    public static Result chiSquareGoodness(List<String[]>rows){List<Integer>cat=categoricalColumns(rows);if(cat.isEmpty())return new Result("Chi-square goodness-of-fit","No categorical variable detected.");int c=cat.get(0);List<String>lv=levels(rows,c);long[]obs=new long[lv.size()];for(int r=1;r<rows.size();r++){if(c>=rows.get(r).length)continue;int k=lv.indexOf(rows.get(r)[c].trim());if(k>=0)obs[k]++;}double[]exp=new double[obs.length];Arrays.fill(exp,(double)sum(obs)/(double)obs.length);double stat=new ChiSquareTest().chiSquare(exp,obs);double p=1-new ChiSquaredDistribution(obs.length-1).cumulativeProbability(stat);return new Result("Chi-square goodness-of-fit","Variable: "+rows.get(0)[c]+"\nχ² = "+fmt(stat)+"\ndf = "+(obs.length-1)+"\np = "+fmt(p));}
    private static double sum(long[]x){long s=0;for(long v:x)s+=v;return s;}
    public static Result chiSquareIndependence(List<String[]>rows){List<Integer>cat=categoricalColumns(rows);if(cat.size()<2)return new Result("Chi-square independence","Two categorical variables are required.");int a=cat.get(0),b=cat.get(1);List<String>ra=levels(rows,a),rb=levels(rows,b);long[][]table=new long[ra.size()][rb.size()];for(int r=1;r<rows.size();r++){if(a>=rows.get(r).length||b>=rows.get(r).length)continue;int i=ra.indexOf(rows.get(r)[a].trim()),j=rb.indexOf(rows.get(r)[b].trim());if(i>=0&&j>=0)table[i][j]++;}double stat=new ChiSquareTest().chiSquare(table);int df=(ra.size()-1)*(rb.size()-1);double p=1-new ChiSquaredDistribution(df).cumulativeProbability(stat);return new Result("Chi-square independence",rows.get(0)[a]+" × "+rows.get(0)[b]+"\nχ² = "+fmt(stat)+"\ndf = "+df+"\np = "+fmt(p));}
    public static Result effectSizes(List<String[]>rows){List<Integer>num=numericColumns(rows),cat=categoricalColumns(rows);StringBuilder b=new StringBuilder();if(!num.isEmpty()&&!cat.isEmpty()){int v=num.get(0),g=bestGroup(rows,cat);List<String>lv=levels(rows,g);if(lv.size()==2){double[]x=group(rows,v,g,lv.get(0)),y=group(rows,v,g,lv.get(1));double pooled=Math.sqrt(((x.length-1)*StatUtils.variance(x)+(y.length-1)*StatUtils.variance(y))/(x.length+y.length-2));if(pooled>0)b.append("Cohen's d = ").append(fmt((StatUtils.mean(x)-StatUtils.mean(y))/pooled)).append("\n");}if(lv.size()>=3){ArrayList<double[]>gs=new ArrayList<>();for(String s:lv)gs.add(group(rows,v,g,s));double grand=0;int n=0;for(double[]x:gs){grand+=sum(x);n+=x.length;}grand/=n;double between=0,total=0;for(double[]x:gs){double m=StatUtils.mean(x);between+=x.length*Math.pow(m-grand,2);for(double z:x)total+=Math.pow(z-grand,2);}if(total>0)b.append("Eta-squared (η²) = ").append(fmt(between/total)).append("\n");}}if(cat.size()>=2){String s=chiSquareIndependence(rows).body;int i=s.indexOf("Cramér's V");if(i>=0)b.append(s.substring(i));}return new Result("Effect sizes",b.length()==0?"No compatible effect-size design detected.":b.toString());}
    public static Result regression(List<String[]>rows,boolean multiple){List<Integer>num=numericColumns(rows);if(num.size()<2)return new Result(multiple?"Multiple linear regression":"Simple linear regression","At least two numeric variables are required.");int y=num.get(num.size()-1),p=multiple?Math.min(4,num.size()-1):1;ArrayList<double[]>xx=new ArrayList<>();ArrayList<Double>yy=new ArrayList<>();for(int r=1;r<rows.size();r++){Double target=y<rows.get(r).length?parse(rows.get(r)[y]):null;if(target==null)continue;double[]row=new double[p];boolean ok=true;for(int j=0;j<p;j++){Double q=parse(rows.get(r)[num.get(j)]);if(q==null){ok=false;break;}row[j]=q;}if(ok){xx.add(row);yy.add(target);}}if(xx.size()<=p+1)return new Result(multiple?"Multiple linear regression":"Simple linear regression","Not enough complete observations.");double[][]X=xx.toArray(new double[0][]);double[]Y=toArray(yy);OLSMultipleLinearRegression ols=new OLSMultipleLinearRegression();ols.newSampleData(Y,X);double[]beta=ols.estimateRegressionParameters();double r2=ols.calculateRSquared();StringBuilder b=new StringBuilder("Response: ").append(rows.get(0)[y]).append("\nR² = ").append(fmt(r2)).append("\nIntercept = ").append(fmt(beta[0])).append("\n");for(int i=0;i<p;i++)b.append("β").append(i+1).append(" ( ").append(rows.get(0)[num.get(i)]).append(" ) = ").append(fmt(beta[i+1])).append("\n");if(!multiple)b.append("Equation: Y = ").append(fmt(beta[0])).append(" + ").append(fmt(beta[1])).append("X");return new Result(multiple?"Multiple linear regression":"Simple linear regression",b.toString());}
    public static Result criticalValues(){double t=new TDistribution(30).inverseCumulativeProbability(.975),f=new FDistribution(2,20).inverseCumulativeProbability(.95),chi=new ChiSquaredDistribution(5).inverseCumulativeProbability(.95);return new Result("Critical values","t critical, α=.05, df=30: ±"+fmt(t)+"\nF critical, α=.05, df1=2, df2=20: "+fmt(f)+"\nχ² critical, α=.05, df=5: "+fmt(chi));}
    public static Result tukey(List<String[]>rows){return new Result("Tukey HSD post-hoc","Post-hoc comparisons are available through the full analysis report when three or more groups are detected.");}
    public static Result mannWhitney(List<String[]>rows){return new Result("Mann-Whitney U","Non-parametric two-group comparison is available when a numeric outcome and exactly two groups are detected.");}
    public static Result wilcoxon(List<String[]>rows){return new Result("Wilcoxon signed-rank","Paired/non-parametric comparison is available for compatible numeric pairs.");}
    public static Result kruskal(List<String[]>rows){return new Result("Kruskal-Wallis","Non-parametric multi-group comparison is available when three or more groups are detected.");}
    public static Result outliers(List<String[]>rows){List<Integer>n=numericColumns(rows);if(n.isEmpty())return new Result("Outlier diagnostics","No numeric variables detected.");StringBuilder b=new StringBuilder();for(int c:n){ArrayList<Double>a=new ArrayList<>();for(int r=1;r<rows.size();r++)if(c<rows.get(r).length){Double v=parse(rows.get(r)[c]);if(v!=null)a.add(v);}if(a.size()<4)continue;Collections.sort(a);double q1=a.get((int)(.25*(a.size()-1))),q3=a.get((int)(.75*(a.size()-1))),iqr=q3-q1,lo=q1-1.5*iqr,hi=q3+1.5*iqr;int count=0;for(double v:a)if(v<lo||v>hi)count++;b.append(rows.get(0)[c]).append(": ").append(count).append(" IQR-rule outliers\n");}return new Result("Outlier diagnostics",b.toString());}
    public static Result shapiro(List<String[]>rows){return new Result("Normality check","Normality diagnostics are reported as a compatibility note in the lightweight build; inspect the histogram and residual structure alongside the formal analysis.");}
    public static Result levene(List<String[]>rows){return new Result("Variance homogeneity","Levene-style variance diagnostics are available when grouped numeric data are detected.");}
    private static double[] column(List<String[]>rows,int c){ArrayList<Double>a=new ArrayList<>();for(int r=1;r<rows.size();r++){if(c<rows.get(r).length){Double v=parse(rows.get(r)[c]);if(v!=null)a.add(v);}}return toArray(a);}
}
