plugins {
    id 'com.android.application'
    id 'com.chaquo.python'
}

android {
    namespace 'com.yugen.statsyuri'
    compileSdk 35

    defaultConfig {
        applicationId 'com.yugen.statsyuri'
        minSdk 24
        targetSdk 35
        versionCode 3
        versionName '0.3.0'

        ndk {
            abiFilters 'arm64-v8a', 'x86_64'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

chaquopy {
    defaultConfig {
        version = "3.10"

        pip {
            install "numpy"
            install "pandas"
            install "scipy"
            install "statsmodels"
            install "openpyxl"
            install "xlrd"
        }
    }

    sourceSets {
        main {
            srcDirs = ["../../yugen-analytica", "src/main/python"]
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.activity:activity:1.10.1'
}
