import 'dart:convert';
import 'dart:math' as math;
import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

const bg = Color(0xFF0B0E14), bg2 = Color(0xFF121620), card = Color(0xFF1A1F2C), surface = Color(0xFF242B3D), accent = Color(0xFFC9A9FF), cyan = Color(0xFF8DD8FF);

void main() => runApp(const StatsYuriApp());

class StatsYuriApp extends StatelessWidget {
  const StatsYuriApp({super.key});
  @override Widget build(BuildContext context) => MaterialApp(
    title: 'StatsYuri', debugShowCheckedModeBanner: false,
    theme: ThemeData(brightness: Brightness.dark, useMaterial3: true, scaffoldBackgroundColor: bg,
      colorScheme: const ColorScheme.dark(primary: accent, secondary: cyan, surface: card),
      inputDecorationTheme: const InputDecorationTheme(filled: true, fillColor: surface,
        contentPadding: EdgeInsets.symmetric(horizontal: 16, vertical: 15),
        border: OutlineInputBorder(borderRadius: BorderRadius.all(Radius.circular(16)), borderSide: BorderSide.none),
        enabledBorder: OutlineInputBorder(borderRadius: BorderRadius.all(Radius.circular(16)), borderSide: BorderSide.none),
        focusedBorder: OutlineInputBorder(borderRadius: BorderRadius.all(Radius.circular(16)), borderSide: BorderSide(color: accent, width: 1.2)))),
    home: const Home());
}

class Home extends StatefulWidget { const Home({super.key}); @override State<Home> createState() => _HomeState(); }
class _HomeState extends State<Home> with SingleTickerProviderStateMixin {
  static const channel = MethodChannel('statsyuri/python');
  String? path, name, error; String question = '', mode = 'efficient'; bool busy = false; Map<String,dynamic>? result;
  late AnimationController animation;
  @override void initState(){super.initState(); animation=AnimationController(vsync:this,duration:const Duration(seconds:22))..repeat();}
  @override void dispose(){animation.dispose();super.dispose();}
  Future<void> pick() async { final p=await FilePicker.platform.pickFiles(type:FileType.custom,allowedExtensions:['csv','xlsx','xls']); if(p?.files.single.path==null)return; setState((){path=p!.files.single.path;name=p.files.single.name;result=null;error=null;}); }
  Future<void> analyze() async {
    if(path==null){setState(()=>error='Choose a CSV or Excel dataset first.');return;}
    setState(()=>{busy=true,error=null,result=null});
    try { final raw=await channel.invokeMethod<String>('analyze',{'path':path,'question':question.trim(),'mode':mode}); final x=jsonDecode(raw??'{}'); setState(()=>result=Map<String,dynamic>.from(x)); }
    on PlatformException catch(e){setState(()=>error=e.message??e.code);} catch(e){setState(()=>error=e.toString());} finally{if(mounted)setState(()=>busy=false);}
  }
  @override Widget build(BuildContext context)=>Scaffold(
    appBar:AppBar(backgroundColor:Colors.transparent,surfaceTintColor:Colors.transparent,titleSpacing:18,title:const Row(children:[Mark(34),SizedBox(width:10),Text('StatsYuri',style:TextStyle(fontWeight:FontWeight.w900))]),actions:[Container(margin:const EdgeInsets.only(right:16),padding:const EdgeInsets.symmetric(horizontal:10,vertical:6),decoration:BoxDecoration(color:surface,borderRadius:BorderRadius.circular(30)),child:const Text('OFFLINE',style:TextStyle(fontSize:10,fontWeight:FontWeight.w900))) ]),
    body:Stack(children:[Positioned.fill(child:AnimatedBuilder(animation:animation,builder:(_,__)=>CustomPaint(painter:DataBg(animation.value)))),SafeArea(child:ListView(padding:const EdgeInsets.fromLTRB(18,10,18,42),children:[
      Row(crossAxisAlignment:CrossAxisAlignment.start,children:[const Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Statistical Analysis',style:TextStyle(fontSize:27,fontWeight:FontWeight.w900)),SizedBox(height:7),Text('Analyze locally. See the reasoning and calculations without sending your data anywhere.',style:TextStyle(color:Colors.white60,fontSize:14,height:1.45))])),const SizedBox(width:12),const Mark(58)]),
      const SizedBox(height:20),
      CardBox(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const TitleRow(Icons.dataset_rounded,'Dataset'),const SizedBox(height:12),InkWell(onTap:busy?null:pick,borderRadius:BorderRadius.circular(16),child:Container(width:double.infinity,padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:surface,borderRadius:BorderRadius.circular(16)),child:Row(children:[const Icon(Icons.upload_file_rounded,color:cyan),const SizedBox(width:12),Expanded(child:Text(name??'Choose CSV / Excel dataset',style:TextStyle(fontWeight:FontWeight.w800))),const Icon(Icons.chevron_right_rounded)])))])),
      const SizedBox(height:14),
      CardBox(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const TitleRow(Icons.auto_awesome_rounded,'Ask StatsYuri'),const SizedBox(height:6),const Text('Optional. Leave it empty and StatsYuri will analyze the dataset automatically.',style:TextStyle(color:Colors.white60,fontSize:13,height:1.4)),const SizedBox(height:13),TextField(minLines:3,maxLines:6,onChanged:(v)=>question=v,style:const TextStyle(fontSize:15,height:1.45),decoration:const InputDecoration(hintText:'Example: Do crop yields differ among fertilizer groups?')),const SizedBox(height:14),Container(padding:const EdgeInsets.all(4),decoration:BoxDecoration(color:surface,borderRadius:BorderRadius.circular(17)),child:SegmentedButton<String>(showSelectedIcon:false,segments:const[ButtonSegment(value:'efficient',label:Text('Efficient'),icon:Icon(Icons.bolt_rounded,size:18)),ButtonSegment(value:'full',label:Text('Full analysis'),icon:Icon(Icons.analytics_rounded,size:18))],selected:{mode},onSelectionChanged:(v)=>setState(()=>mode=v.first))),const SizedBox(height:10),Text(mode=='full'?'Full mode checks every compatible analysis it can calculate from this dataset.':'Efficient mode selects one compatible analysis and explains it.',style:const TextStyle(color:Colors.white38,fontSize:12)),const SizedBox(height:14),SizedBox(width:double.infinity,child:FilledButton.icon(onPressed:busy?null:analyze,style:FilledButton.styleFrom(backgroundColor:accent,foregroundColor:Color(0xFF25183E),padding:const EdgeInsets.symmetric(vertical:16),shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(18))),icon:busy?const SizedBox(width:18,height:18,child:CircularProgressIndicator(strokeWidth:2)):const Icon(Icons.search_rounded),label:Text(busy?'Analyzing…':'Analyze dataset',style:const TextStyle(fontWeight:FontWeight.w900,fontSize:15))))])),
      if(error!=null)Padding(padding:const EdgeInsets.only(top:14),child:CardBox(child:Row(crossAxisAlignment:CrossAxisAlignment.start,children:[const Icon(Icons.error_outline_rounded,color:Color(0xFFFF9B9B)),const SizedBox(width:10),Expanded(child:Text(error!,style:const TextStyle(fontSize:14,height:1.4)))]))),
      if(result!=null)Output(result!),
    ]))]));
}

class CardBox extends StatelessWidget{const CardBox({super.key,required this.child});final Widget child;@override Widget build(BuildContext c)=>Container(padding:const EdgeInsets.all(18),decoration:BoxDecoration(color:card.withOpacity(.95),borderRadius:BorderRadius.circular(22),border:Border.all(color:Colors.white.withOpacity(.055)),boxShadow:[BoxShadow(color:Colors.black.withOpacity(.18),blurRadius:24,offset:const Offset(0,10))]),child:child);}
class TitleRow extends StatelessWidget{const TitleRow(this.icon,this.text,{super.key});final IconData icon;final String text;@override Widget build(BuildContext c)=>Row(children:[Icon(icon,color:accent,size:21),const SizedBox(width:9),Text(text,style:const TextStyle(fontSize:18,fontWeight:FontWeight.w900))]);}
class Mark extends StatelessWidget{const Mark(this.size,{super.key});final double size;@override Widget build(BuildContext c)=>Container(width:size,height:size,decoration:BoxDecoration(borderRadius:BorderRadius.circular(size*.28),gradient:const LinearGradient(colors:[accent,cyan]),boxShadow:[BoxShadow(color:Color(0x30C9A9FF),blurRadius:18)]),child:CustomPaint(painter:MarkPainter()));}
class MarkPainter extends CustomPainter{@override void paint(Canvas c,Size s){final w=s.width,stroke=Paint()..color=const Color(0xFF141826)..style=PaintingStyle.stroke..strokeWidth=w*.08..strokeCap=StrokeCap.round,fill=Paint()..color=const Color(0xFF141826);c.drawLine(Offset(w*.18,w*.78),Offset(w*.82,w*.78),stroke);for(final b in[[.23,.53,.09,.25],[.40,.39,.09,.39],[.57,.26,.09,.52]])c.drawRRect(RRect.fromRectAndRadius(Rect.fromLTWH(w*b[0],w*b[1],w*b[2],w*b[3]),Radius.circular(w*.03)),fill);final p=Path()..moveTo(w*.30,w*.23)..lineTo(w*.48,w*.23)..lineTo(w*.35,w*.39)..lineTo(w*.50,w*.55);c.drawPath(p,stroke);}@override bool shouldRepaint(covariant CustomPainter o)=>false;}

class Output extends StatelessWidget{const Output(this.r,{super.key});final Map<String,dynamic> r;@override Widget build(BuildContext c){final full=r['mode']=='full',items=r['analyses'];return Padding(padding:const EdgeInsets.only(top:16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[CardBox(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Icon(r['ok']==true?Icons.check_circle_rounded:Icons.info_rounded,color:r['ok']==true?const Color(0xFF9FE7C4):const Color(0xFFFFD27D),size:25),const SizedBox(width:10),Expanded(child:Text(full?'Full analysis':pretty(r['analysis']?.toString()??'Analysis'),style:const TextStyle(fontSize:21,fontWeight:FontWeight.w900)))]),const SizedBox(height:8),Text(full?'${r['analysis_count']??0} compatible analyses evaluated.':'Analysis completed locally on your device.',style:const TextStyle(color:Colors.white60,fontSize:13.5)),const SizedBox(height:13),Wrap(spacing:8,runSpacing:8,children:[if(r['rows']!=null)Metric('Rows','${r['rows']}'),if(r['columns']is List)Metric('Columns','${(r['columns']as List).length}')])])),if(full&&items is List)...items.asMap().entries.map((e)=>AnalysisCard(Map<String,dynamic>.from(e.value),e.key+1))else AnalysisCard(r,1)]));}}
class Metric extends StatelessWidget{const Metric(this.a,this.b,{super.key});final String a,b;@override Widget build(BuildContext c)=>Container(padding:const EdgeInsets.symmetric(horizontal:12,vertical:8),decoration:BoxDecoration(color:surface,borderRadius:BorderRadius.circular(12)),child:Text('$a  $b',style:const TextStyle(fontSize:12.5,fontWeight:FontWeight.w800)));}
class AnalysisCard extends StatelessWidget{const AnalysisCard(this.r,this.i,{super.key});final Map<String,dynamic> r;final int i;@override Widget build(BuildContext c){final values=r['result'],calc=r['calculation'];return Padding(padding:const EdgeInsets.only(top:12),child:CardBox(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Container(width:30,height:30,alignment:Alignment.center,decoration:BoxDecoration(color:accent.withOpacity(.13),borderRadius:BorderRadius.circular(10)),child:Text('$i',style:const TextStyle(color:accent,fontWeight:FontWeight.w900))),const SizedBox(width:11),Expanded(child:Text(pretty(r['analysis']?.toString()??'Analysis'),style:const TextStyle(fontSize:19,fontWeight:FontWeight.w900)))]),const SizedBox(height:6),Row(children:[Icon(r['ok']==true?Icons.verified_rounded:Icons.info_outline_rounded,size:16,color:r['ok']==true?const Color(0xFF9FE7C4):const Color(0xFFFFD27D)),const SizedBox(width:6),Text(r['ok']==true?'Calculated':'Could not calculate',style:const TextStyle(fontSize:12.5,fontWeight:FontWeight.w700))]),if(r['reason']!=null)...[const SizedBox(height:14),Block('Why this analysis',Text(r['reason'].toString(),style:const TextStyle(color:Colors.white70,fontSize:14,height:1.5)))],if(values is Map)...[const SizedBox(height:14),Block('Results',Grid(Map<String,dynamic>.from(values)))],if(calc is Map)...[const SizedBox(height:14),Block('Calculation',Calculation(Map<String,dynamic>.from(calc)))],if(r['error']!=null)...[const SizedBox(height:12),Text(r['error'].toString(),style:const TextStyle(color:Color(0xFFFFB0B0),fontSize:13.5))]])));}}
class Block extends StatelessWidget{const Block(this.title,this.child,{super.key});final String title;final Widget child;@override Widget build(BuildContext c)=>Container(width:double.infinity,padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:surface.withOpacity(.72),borderRadius:BorderRadius.circular(16)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title.toUpperCase(),style:const TextStyle(color:accent,fontSize:11,fontWeight:FontWeight.w900,letterSpacing:.7)),const SizedBox(height:8),child]));}
class Grid extends StatelessWidget{const Grid(this.data,{super.key});final Map<String,dynamic> data;@override Widget build(BuildContext c)=>LayoutBuilder(builder:(c,box){final two=box.maxWidth>=470;return Wrap(spacing:9,runSpacing:9,children:data.entries.map((e){final w=two?(box.maxWidth-9)/2:box.maxWidth;final v=e.value;if(v is Map||v is List)return SizedBox(width:w,child:ExpansionTile(tilePadding:const EdgeInsets.symmetric(horizontal:13),backgroundColor:card,collapsedBackgroundColor:card,title:Text(keyName(e.key),style:const TextStyle(fontWeight:FontWeight.w800)),children:[Padding(padding:const EdgeInsets.fromLTRB(13,0,13,12),child:Text(valueText(v),style:const TextStyle(fontSize:13.5,height:1.5)))]));return SizedBox(width:w,child:Container(padding:const EdgeInsets.symmetric(horizontal:13,vertical:12),decoration:BoxDecoration(color:card,borderRadius:BorderRadius.circular(13)),child:Row(crossAxisAlignment:CrossAxisAlignment.start,children:[Expanded(child:Text(keyName(e.key),style:const TextStyle(color:Colors.white60,fontSize:13))),const SizedBox(width:12),Flexible(child:Text(valueText(v),textAlign:TextAlign.right,style:const TextStyle(fontSize:15,fontWeight:FontWeight.w900)))])));}).toList());});}
class Calculation extends StatelessWidget{const Calculation(this.data,{super.key});final Map<String,dynamic> data;@override Widget build(BuildContext c){final steps=data['steps'];return Column(crossAxisAlignment:CrossAxisAlignment.start,children:[if(data['formula']!=null)Container(width:double.infinity,padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:card,borderRadius:BorderRadius.circular(12)),child:Text(data['formula'].toString(),style:const TextStyle(color:accent,fontWeight:FontWeight.w900,fontSize:14,height:1.4))),if(data['formula']!=null&&steps is List)const SizedBox(height:10),if(steps is List)...steps.asMap().entries.map((e)=>Padding(padding:const EdgeInsets.only(bottom:9),child:Row(crossAxisAlignment:CrossAxisAlignment.start,children:[Container(width:24,height:24,alignment:Alignment.center,decoration:BoxDecoration(color:accent.withOpacity(.14),shape:BoxShape.circle),child:Text('${e.key+1}',style:const TextStyle(fontSize:11,color:accent,fontWeight:FontWeight.w900))),const SizedBox(width:10),Expanded(child:Text(e.value.toString().replaceAll('_',' '),style:const TextStyle(fontSize:14,height:1.45)))])))]);}}
String pretty(String s)=>s.replaceAll(' + simple linear regression',' + Regression');
String keyName(String s){const m={'F-Statistic':'F statistic','P-Value':'p-value','T-Statistic':'t statistic','Degrees of Freedom':'Degrees of freedom','R-Squared':'R²','Slope P-Value':'Slope p-value','Sample Mean':'Sample mean','Hypothesized Mean':'Reference mean','Group Sizes':'Group sizes','Group Means':'Group means','Total Sample Size':'Total sample size','Number of Groups':'Number of groups'};return m[s]??s.replaceAll('_',' ');}
String valueText(dynamic v){if(v==null)return'Not available';if(v is double){if(!v.isFinite)return v.toString();if(v.abs()<.0001&&v!=0)return v.toStringAsExponential(3);return v.toStringAsFixed(5).replaceFirst(RegExp(r'0+$'),'').replaceFirst(RegExp(r'\.$'),'');}if(v is num)return v.toString();if(v is Map)return v.entries.map((e)=>'${keyName(e.key.toString())}: ${valueText(e.value)}').join('\n');if(v is List)return v.map(valueText).join('  •  ');return v.toString();}
class DataBg extends CustomPainter{DataBg(this.p);final double p;@override void paint(Canvas c,Size s){final t=p*math.pi*2;final bgp=Paint()..shader=const LinearGradient(begin:Alignment.topLeft,end:Alignment.bottomRight,colors:[bg,bg2]).createShader(Offset.zero&s);c.drawRect(Offset.zero&s,bgp);for(final b in[(Offset(s.width*(.08+.035*math.sin(t)),s.height*.13),190.0,const Color(0xFF6C4CA0)),(Offset(s.width*(.9+.035*math.cos(t*.8)),s.height*.42),220.0,const Color(0xFF315E7D)),(Offset(s.width*(.52+.06*math.sin(t*.55)),s.height*.88),210.0,const Color(0xFF49376F))]){final q=Paint()..shader=RadialGradient(colors:[b.$3.withOpacity(.095),b.$3.withOpacity(0)]).createShader(Rect.fromCircle(center:b.$1,radius:b.$2));c.drawCircle(b.$1,b.$2,q);}final grid=Paint()..color=Colors.white.withOpacity(.018);const step=42.0;final d=p*step%step;for(double x=-step+d;x<s.width+step;x+=step)c.drawLine(Offset(x,0),Offset(x,s.height),grid);for(double y=-step+d;y<s.height+step;y+=step)c.drawLine(Offset(0,y),Offset(s.width,y),grid);final symbols=['μ','σ','x̄','r','p','Σ','F','t','χ²','β'];for(var i=0;i<symbols.length;i++){final ph=t*(.16+i*.013)+i*1.7,x=((i*97+math.sin(ph)*24)%(s.width+80))-40,y=((i*137+p*180+math.cos(ph)*32)%(s.height+120))-60;final tp=TextPainter(text:TextSpan(text:symbols[i],style:TextStyle(color:accent.withOpacity(.03),fontSize:22+(i%3)*7,fontWeight:FontWeight.w700)),textDirection:TextDirection.ltr)..layout();tp.paint(c,Offset(x,y));}}@override bool shouldRepaint(covariant DataBg o)=>o.p!=p;}
